# Fisker vs Tesla

Based on the *Wall Street Journal* article from August 7, 2020 entitled:

**Car designer Henrik Fisker Lost His First Race with Elon Musk.  He Wants to Go Again.**

1. Identify three ways that Fisker and Musk are strategically approaching developing electric cars differently.   Be specific, be insightful.
2. Why might Fisker have have chosen his route – what makes this easier for him?  Are there dangers to this approach? 
3. Which company has a superior strategic plan – be critical, think carefully. Why? 
4. What do you think of Fisker's chances in the long run?


# Robin Hood

Here are the specifics your Robin Hood presentations:

**We have ALREADY identified Robin Hood's challenges, so...**

Please work in a group of 2 to prepare a presentation (it does not have to be Slides, PowerPoint, Prezi, etc.) approximately 5-7 minutes in length as though you are Robin Hood’s most trusted adviser.

As a group of students studying crafting and implementing effective strategies, he has called upon you to advise him on how to proceed in light of the situation. 
 
Please provide supporting analysis and persuasive argument for your recommended course of action (you must convince him to do what you suggest!) and you need to be specific about what to do and how to do it. You do not have to answer each of the following questions, but consider each of these as develop analysis and recommendations for your presentation.

You do not have to answer all of these questions but you may want to consider:

1. What **KEY** problems does Robin Hood have? What issues **MOST** need to be addressed?
3. What strategic options does Robin Hood have? Is continuing with the  present strategy an option or is the present strategy obsolete?
6. What action plan would you recommend to Robin?  Should he implement a new tax?  If so, how should it be structured?
7. How should Robin implement the recommended plan? What action steps  will need to be taken to make the recommended strategy work successfully?
8. BE CREATIVE!  Should he create farms, franchises, employ a subscription-based model, manufacturing, off-shoring?

# Can You Say

Based on the Harvard Business Review article: *Can you say what your strategy is? By David Collis and Michael Rukstadt, please be prepared to answer the following questions:

1. Summarize briefly, what is the point of this article?  
2. Be able to identify and explain the three core components of the strategy statement along with each of the **sub components**. You will need to know this!!!
3. Make sure you know what the examples in the article mean – what about Red Lobster? What about Boeing?

4. If there's a chart, look at it. If there's a graph, understand it. These are all good – and will be on your quiz. 

5. Think of an organization of your choosing.  How could you apply the ideas of this article to it? Could you write a strategy statement for that organization based on the principles of this article? 

# GM and Ford EVs

Based on the *Wall Street Journal* article from June 22, 2022 entitled:

*GM, Ford turn on each other into EV's,  Detroit's greatest rivalry is intensifying in the race to take on Tesla*

1. Summarize the key differences in how Ford and GM are strategically approaching the EV market
2.  Which company do you believe has the correct or better strategy? 
3. What is the market saying about each strategy? Is there currently a winner and/or loser?
4. Should Tesla be taking note of what these two companies are doing – why or why not? If so, what should Tesla do about it? 

# Chapter 1

## CHAPTER 1 What Is Strategy?

1. Explain the role of strategy in a firm’s quest for competitive advantage. 
2. Define competitive advantage, sustainable competitive advantage, competitive disadvantage, and competitive parity. 
3. Assess the relationship between stakeholder strategy and sustainable competitive advantage. 
4. Conduct a stakeholder impact analysis. 
5. Explain the Analysis, Formulation, Implementation (AFI) Strategy Framework.

## Key Terms

- Analysis, Implementation, Formulation (AFI) Strategy Framework. 
- Competitive advantage.
- Competitive disadvantage. 
- Competitive parity.
- Corporate social responsibility (CSR).
- Good strategy. 
- Stakeholder impact analysis.
- Stakeholder strategy.
- Stakeholders.
- Strategic management. 
- Strategy. 
- Sustainable competitive advantage.
- Value creation.



# Chapter 2

## Strategic Leadership: Managing the Strategy Process

1. Explain the role of strategic leaders and what they do. 
2. Outline how you can become a strategic leader. 
3. Compare and contrast the roles of corporate, business, and functional managers in strategy formulation and implementation. 
4. Describe the roles of vision, mission, and values in a firm’s strategy. 
5. Evaluate the strategic implications of product-oriented and customer-oriented vision statements.
6. Justify why anchoring a firm in ethical core values is essential for long-term success. 
7. Evaluate top-down strategic planning, scenario planning, and strategy as planned emergence. 
8. Describe and evaluate the two distinct modes of decision making. 
9. Compare and contrast devil’s advocacy and dialectic inquiry as frameworks to improve strategic decision making.

## Key Terms

- Autonomous actions.
- Behavioral economics.
- Black swan events. 
- Cognitive biases.
- Cognitive limitations. 
- Confirmation bias. 
- Core values statement.
- Devil’s advocacy.
- Dialectic inquiry. 
- Dominant strategic plan. 
- Emergent strategy. 
- Escalating commitment. 
- Groupthink. 
- Illusion of control. 
- Intended strategy. 
- Level-5 leadership pyramid.
- Mission. 
- Organizational core values.
- Planned emergence. 
- Realized strategy. 
- Reason by analogy. 
- Representativeness. 
- Resource-allocation process (RAP). 
- Scenario planning. 
- Serendipity. 
- Stakeholders. 
- Strategic business unit (SBU). 
- Strategic initiative. 
- Strategic intent. 
- Strategic leadership. 
- Strategic management process. 
- Strategy formulation Strategy implementation.
- System 1. 
- System 2. 
- Theory of bounded rationality. 
- Top-down strategic planning. 
- Upper-echelons theory. 
- Vision.

## [Checkout Popeye's](https://www.bizjournals.com/bizwomen/news/profiles-strategies/2015/05/inside-thepopeyes-turnaround-how-cheryl-bachelder.html?page=all)


# Chapter 3

# Chapter 4

# Chapter 5